#!/usr/bin/env bash
# A Bash script that configures a server = facebook -> 8.8.8.8 and localhost -> 127.0.0.2

cp /etc/hosts ~/hosts.new

echo "" > ~/hosts.new
echo "localhost	 127.0.0.2" >> ~/hosts.new
echo "8.8.8.8	facebook.com" >> ~/hosts.new

cp -f ~/hosts.new /etc/hosts
